### ISSUE TITLE
.env DOMAIN setting appears ignored? 

### ISSUE THREAD

**Issue by K3CAN** [be0vlk/owlculus#2]
Hello! 

I'm not sure if this is a bug or just a misunderstanding on my part. 

In the .env file, I've tried setting `DOMAIN="http://10.0.0.101:5000"` but it appears to revert to the default loop-back interface. 
```
 * Serving Flask app 'app'
 * Debug mode: on
WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on http://127.0.0.1:5000
Press CTRL+C to quit
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 109-976-764
 ```
Trying to access the server via IP address on ports 80 or 5000 both fail. 
The server is debian bookworm and I have the firewall temporarily disabled. 

How can I ensure that it's listening on the right interface?

**Comment by be0vlk** [comment]
Hey there, sorry for the delay in getting back to you. The env variable does not actually impact the Flask server binding. It was mostly intended for CORS and so that you can use the app behind a proxy with SSL for things like generating valid invite links. Personally, I use Caddy but whatever works for you. It's not recommended to run the flask development server for actual production use, but if you do want to change the binding you should be able to by adding the host and port parameters to line 80 in app.py, such as:

main_app.run(host="10.0.0.101", port=5000, debug=os.getenv("DEBUG"))

Let me know if that solves the issue for you and if not I'll look into it further!

**Comment by K3CAN** [comment]
Hey thanks! The plan was to run it behind a proxy, but that still requires changing the listening port since the loopback is only accessible from within the server itself. 

I'll try making those changes tonight and see if that works. Thanks for the help!

**Comment by K3CAN** [comment]
Perfect! 

I had looked through app.py myself to see if there was a `host=127.0.0.1` variable or something but didn't see anything obvious. Adding that to main_app.run worked, though, and I can now access the web interface! 

Thanks for your help!

**Comment by be0vlk** [comment]
Great! I'll go ahead and close this out and I'm adding easier configuration of this to the list of changes for the next update.
